### PR TITLE
Add a basic display to the web interface

### PR DESCRIPTION
**Pull request by greenknot**
See #222.

The web interface is available at http://127.0.0.1:5000/display.html and here is a screenshot:

Screenshot from 2021-07-16 12-18-44

The UI is terrible. Need someone with web skillz :)

### CODE REVIEW

**Comment by greenknot** [comment]
Quick update to make it less atrocious:
 
screenshot-web

The web interface is available at `/` and swagger at `/swagger`. The `left`, `right` and `up` keys can be used instead of the buttons.

I think it's already quite useful, but any enhancement is welcome.

**Comment by greenknot** [comment]
On a side note, this doesn't work well with the Blue device (because the screen is too large, and finger actions aren't implemented).

**Comment by TrAyZeN** [comment]
> Quick update to make it less atrocious:
>  
> screenshot-web
> 
> The web interface is available at `/` and swagger at `/swagger`. The `left`, `right` and `up` keys can be used instead of the buttons.
> 
> I think it's already quite useful, but any enhancement is welcome.

Hi, it's great. As an enhancement, I think it would be better to put the `both` button in the middle.

**Comment by niooss-ledger** [comment]
> Hi, it's great. As an enhancement, I think it would be better to put the both button in the middle.

Done, as part of https://github.com/LedgerHQ/speculos/pull/223/commits/507dc73949e576305e75611b6080aea2d6a53f5f ("api: add alt and title texts").

I directly modified the Pull Request with some improvements, and with them, this looks good to me :+1:

**Review by niooss-ledger — APPROVED** [review]

**Pull request merged**
